services:
  db:
    image: postgres:15 # VersÃ£o estÃ¡vel e moderna ğŸ˜
    container_name: tasktracker-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}      # LÃª do arquivo .env
      - POSTGRES_PASSWORD=${DB_PASSWORD} # LÃª do arquivo .env
      - POSTGRES_DB=tasktracker_db
    ports:
      - "5432:5432" # Mapeia a porta padrÃ£o do Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data # Garante que seus dados nÃ£o sumam se o container parar

volumes:
  postgres_data:
